# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stockService_pb2 as stockService__pb2


class StockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductsFromCountry = channel.unary_unary(
                '/StockService/GetProductsFromCountry',
                request_serializer=stockService__pb2.CountryProduct.SerializeToString,
                response_deserializer=stockService__pb2.GetProductFromCountryPayload.FromString,
                )


class StockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductsFromCountry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductsFromCountry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsFromCountry,
                    request_deserializer=stockService__pb2.CountryProduct.FromString,
                    response_serializer=stockService__pb2.GetProductFromCountryPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductsFromCountry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StockService/GetProductsFromCountry',
            stockService__pb2.CountryProduct.SerializeToString,
            stockService__pb2.GetProductFromCountryPayload.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
